export const ERROR = 'ERROR';

export const FETCH_SERVER_REQUEST = 'FETCH_SERVER_REQUEST';
export const FETCH_SERVER_SUCCESS = 'FETCH_SERVER_SUCCESS';
export const FETCH_SERVER_FAILURE = 'FETCH_SERVER_FAILURE';

export const ADD_TASK = 'ADD_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const COMPLETE_TASK = 'COMPLETE_TASK';
export const START_TASK = 'START_TASK';

export const FILTER_TASKS = 'FILTER_TASKS';
export const SEARCH_TASKS = 'SEARCH_TASKS';